pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: shell
    image: alpine:3.19
    command: ['cat']
    tty: true
"""
    }
  }

  stages {

    stage('Checkout') {
      steps {
        git branch: 'main',
            url: 'https://github.com/mjkim740/iac-lab.git'
      }
    }

    stage('Web CI') {
      steps {
        container('shell') {
          sh 'cd cicd/web && ./ci.sh'
        }
      }
    }

    stage('WAS CI') {
      steps {
        container('shell') {
          sh 'cd cicd/was && ./ci.sh'
        }
      }
    }

    stage('DB CI') {
      steps {
        container('shell') {
          sh 'cd cicd/db && ./ci.sh'
        }
      }
    }
  }
}

